import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { AVATAR_COLORS } from "@/lib/utils";
import type { PlayerProfile } from "@/hooks/use-player";
import { User, Palette, AlertCircle, Trophy, Gamepad2, LogIn } from "lucide-react";
import { signInWithGoogle, signInWithFacebook, signInWithTikTok, signInWithApple, checkOAuthReturn, consumeFacebookAccessToken, isGoogleConfigured, isFacebookConfigured, isTikTokConfigured, isAppleConfigured, type OAuthUser } from "@/lib/oauth";
import { useT } from "@/i18n/useT";
import { LanguageSelector } from "./LanguageSelector";

const LOGO_URL = `${import.meta.env.BASE_URL}images/stop-logo.png`;
interface AuthModalProps { onSave:(profile:PlayerProfile)=>void; initial?:PlayerProfile|null; onDismiss?:()=>void; }

export function AuthModal({onSave,initial,onDismiss}:AuthModalProps){
 const {t}=useT();
 const [step,setStep]=useState<"login"|"profile"|"welcome_back">(initial?"profile":"login");
 const [guest,setGuest]=useState(false);
 const [name,setName]=useState(initial?.name||"");
 const [avatarColor,setAvatarColor]=useState(initial?.avatarColor||AVATAR_COLORS[0]);
 const [loginMethod,setLoginMethod]=useState<string|null>(null);
 const [oauthPicture,setOauthPicture]=useState<string|null>(null);
 const [oauthId,setOauthId]=useState<string|null>(null);
 const [fbToken,setFbToken]=useState<string|null>(null);
 const [error,setError]=useState<string|null>(null);
 const [existingStats,setExistingStats]=useState<{totalScore:number;gamesPlayed:number}|null>(null);
 useEffect(()=>{try{const u=checkOAuthReturn();if(u){const token=consumeFacebookAccessToken();if(token)setFbToken(token);handleOAuthSuccess(u,token);}}catch(e:any){setError(e.message||"Error.");}},[]);
 const handleOAuthSuccess=(u:OAuthUser,token:string|null=null)=>{setOauthId(u.id);setLoginMethod(u.provider);setName((u.name||"").slice(0,14));setOauthPicture(u.picture||null);setError(null);setGuest(false);setStep("profile");const apiBase=(import.meta as any).env?.VITE_API_URL??window.location.origin;fetch(`${apiBase}/api/ranking/scores/${encodeURIComponent(u.id)}`).then(r=>r.ok?r.json():null).then(d=>{if(d?.score?.gamesPlayed>0){setExistingStats({totalScore:d.score.totalScore,gamesPlayed:d.score.gamesPlayed});setStep("welcome_back");setTimeout(()=>onSave({id:u.id,name:(u.name||"").slice(0,14),avatarColor:AVATAR_COLORS[u.id.split("").reduce((a,c)=>a+c.charCodeAt(0),0)%AVATAR_COLORS.length],loginMethod:u.provider,picture:u.picture||null,fbAccessToken:token} as any),2000);}}).catch(()=>{});};
 const save=()=>{const clean=name.trim().slice(0,14);if(!clean){setError("Escribe un nombre para jugar.");return;}const id=oauthId||initial?.id||crypto.randomUUID();onSave({id,name:clean,avatarColor,loginMethod:guest?null:loginMethod,picture:oauthPicture,fbAccessToken:fbToken||initial?.fbAccessToken||null} as any);};
 return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/75 backdrop-blur-md"/>
  <motion.div initial={{scale:.88,opacity:0,y:24}} animate={{scale:1,opacity:1,y:0}} transition={{type:"spring",bounce:.32}} className="relative z-10 w-full max-w-sm">
   <div className="rounded-[28px] overflow-hidden shadow-2xl" style={{background:"linear-gradient(145deg,#18237d 0%,#080f45 100%)",border:"1px solid rgba(249,168,37,.45)"}}>
    <div className="text-center pt-7 pb-5 px-6 relative">{onDismiss&&step==="login"&&<button onClick={onDismiss} aria-label="Cerrar" className="absolute top-3 left-3 w-9 h-9 rounded-full bg-white/5 text-white/60 hover:text-white">✕</button>}<div className="absolute top-3 right-3"><LanguageSelector/></div><img src={LOGO_URL} alt="STOP" className="mx-auto mb-3 w-20 h-20 rounded-full shadow-xl"/><h2 className="text-2xl font-black text-white">{step==="login"?(guest?"Jugar como invitado":t.auth.title):step==="welcome_back"?"¡Qué bueno verte de nuevo!":"Crea tu perfil"}</h2><p className="text-white/55 text-sm mt-1">{step==="login"?(guest?"Sin registro. Entra y empieza a jugar.":t.auth.subtitle):step==="welcome_back"?"Recuperando tu progreso…":"Personaliza tu jugador"}</p></div>
    <AnimatePresence>{error&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}} className="mx-6 mb-3 flex items-center gap-2 bg-red-500/15 border border-red-400/30 rounded-xl px-3 py-2 text-red-200 text-sm"><AlertCircle className="w-4 h-4"/>{error}</motion.div>}</AnimatePresence>
    <div className="px-6 pb-7">
     <AnimatePresence mode="wait">
      {step==="welcome_back"?<motion.div key="back" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} className="flex flex-col items-center gap-4 py-3 text-center">{oauthPicture?<img src={oauthPicture} alt="avatar" className="w-20 h-20 rounded-full border-4 border-[#f9a825] object-cover"/>:<div className="w-20 h-20 rounded-full" style={{background:avatarColor}}/>}<p className="text-white font-black text-xl">¡Bienvenido de vuelta, {name}!</p>{existingStats&&<div className="w-full rounded-2xl p-4 bg-white/5 border border-white/10 flex items-center gap-3"><Trophy className="w-7 h-7 text-[#f9a825]"/><div className="text-left"><b className="text-[#f9a825]">{existingStats.totalScore.toLocaleString()} pts</b><div className="text-white/45 text-xs">{existingStats.gamesPlayed} partidas</div></div></div>}</motion.div>:
      step==="login"&&!guest?<motion.div key="login" initial={{opacity:0,x:15}} animate={{opacity:1,x:0}} className="space-y-3"><SocialButton onClick={signInWithGoogle} configured={isGoogleConfigured} label={t.auth.google} bg="white" textColor="#333" icon="G" soonLabel={t.auth.soon}/><SocialButton onClick={signInWithFacebook} configured={isFacebookConfigured} label={t.auth.facebook} bg="#1877F2" textColor="white" icon="f" soonLabel={t.auth.soon}/>{isTikTokConfigured&&<SocialButton onClick={signInWithTikTok} configured label="TikTok" bg="#000" textColor="white" icon="♪" soonLabel={t.auth.soon}/>} {isAppleConfigured&&<SocialButton onClick={signInWithApple} configured label="Apple" bg="#000" textColor="white" icon="" soonLabel={t.auth.soon}/>}<div className="flex items-center gap-3 py-1"><div className="h-px bg-white/10 flex-1"/><span className="text-white/30 text-xs">{t.auth.or}</span><div className="h-px bg-white/10 flex-1"/></div><button onClick={()=>{setGuest(true);setError(null);}} className="w-full rounded-2xl p-4 text-left border border-[#f9a825]/50 bg-gradient-to-r from-[#f9a825]/20 to-transparent hover:from-[#f9a825]/30 transition"><div className="flex items-center gap-3"><span className="w-11 h-11 rounded-xl bg-[#f9a825] text-[#111] flex items-center justify-center"><Gamepad2 className="w-6 h-6"/></span><span className="flex-1"><b className="block text-white">Jugar como invitado</b><small className="text-white/45">Sin registro · entra directamente a jugar</small></span><span className="text-[#f9a825] text-xl">›</span></div></button></motion.div>:
      <motion.div key="profile" initial={{opacity:0,x:15}} animate={{opacity:1,x:0}} className="space-y-4"><div className="rounded-2xl bg-white/5 border border-white/10 p-4"><label className="text-white/70 text-sm flex items-center gap-2 mb-2"><User className="w-4 h-4"/>¿Cómo te llamamos?</label><input autoFocus value={name} onChange={e=>{setName(e.target.value.slice(0,14));setError(null)}} placeholder="Tu nombre de jugador" maxLength={14} className="w-full px-4 py-3.5 rounded-xl bg-black/20 border border-white/10 text-white placeholder-white/25 outline-none focus:border-[#f9a825]"/><p className="text-white/30 text-[11px] mt-2">Máximo 14 caracteres</p></div><div><label className="text-white/60 text-sm flex items-center gap-2 mb-2"><Palette className="w-4 h-4"/>Elige tu color</label><div className="grid grid-cols-6 gap-2">{AVATAR_COLORS.map(c=><button key={c} onClick={()=>setAvatarColor(c)} aria-label={`Color ${c}`} className="w-9 h-9 rounded-full border-2" style={{background:c,borderColor:avatarColor===c?"white":"transparent"}}/>)}</div></div><button onClick={save} className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-[#f9a825] to-[#ffca3a] text-[#17120a] font-black shadow-lg hover:brightness-110 transition flex items-center justify-center gap-2"><LogIn className="w-5 h-5"/>ENTRAR Y JUGAR</button>{guest&&<button onClick={()=>{setGuest(false);setError(null)}} className="w-full py-2 text-white/40 text-xs">← Volver a opciones de acceso</button>}</motion.div>}
     </AnimatePresence></div>
   </div></motion.div></div>;
}
function SocialButton({onClick,configured,icon,label,bg,textColor,soonLabel}:{onClick:()=>void;configured:boolean;icon:string;label:string;bg:string;textColor:string;soonLabel:string}){return <button onClick={configured?onClick:undefined} disabled={!configured} className="w-full flex items-center gap-3 px-4 py-3.5 rounded-xl font-bold transition disabled:opacity-50" style={{background:bg,color:textColor}}><span className="w-7 h-7 rounded-lg bg-black/5 flex items-center justify-center font-black">{icon}</span><span className="flex-1 text-left">{label}</span>{!configured&&<span className="text-xs opacity-60">{soonLabel}</span>}</button>}
