import { ReactNode, useState } from "react";
import { Link } from "wouter";
import { usePlayer } from "@/hooks/use-player";
import { Trophy, Home, User, Crown, Settings } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Button, Input } from "./ui";

export function Layout({ children }: { children: ReactNode }) {
  const { player, isLoaded, updateProfile } = usePlayer();
  const [showProfile, setShowProfile] = useState(false);
  const [showPremium, setShowPremium] = useState(false);
  const [editName, setEditName] = useState("");

  if (!isLoaded) return null;

  const handleSaveProfile = () => {
    if (editName.trim()) {
      updateProfile({ name: editName.trim() });
    }
    setShowProfile(false);
  };

  return (
    <div className="min-h-screen flex flex-col relative overflow-hidden">
      {/* Decorative background image generated by tool */}
      <div 
        className="absolute inset-0 opacity-10 pointer-events-none mix-blend-overlay"
        style={{ backgroundImage: `url(${import.meta.env.BASE_URL}images/game-bg-pattern.png)`, backgroundSize: 'cover' }}
      />

      <header className="w-full p-4 flex items-center justify-between z-10 max-w-5xl mx-auto">
        <Link href="/" className="flex items-center gap-2 hover:scale-105 transition-transform">
          <div className="bg-white text-background px-3 py-1 rounded-lg font-display font-bold text-2xl shadow-md rotate-[-2deg]">
            STOP
          </div>
        </Link>

        <div className="flex items-center gap-3">
          <button 
            onClick={() => setShowPremium(true)}
            className="hidden sm:flex items-center gap-1 bg-gradient-to-r from-yellow-400 to-yellow-600 text-black px-3 py-1.5 rounded-full font-bold text-sm shadow-md hover:shadow-lg transition-all hover:-translate-y-0.5"
          >
            <Crown className="w-4 h-4" /> PRO
          </button>
          
          <button 
            onClick={() => {
              setEditName(player?.name || "");
              setShowProfile(true);
            }}
            className="flex items-center gap-2 bg-black/20 hover:bg-black/30 transition-colors rounded-full pl-2 pr-4 py-1.5 backdrop-blur-sm"
          >
            <div 
              className="w-8 h-8 rounded-full shadow-inner border-2 border-white/50 flex items-center justify-center text-white font-bold text-sm"
              style={{ backgroundColor: player?.avatarColor }}
            >
              {player?.name?.charAt(0).toUpperCase()}
            </div>
            <span className="font-semibold text-white truncate max-w-[100px]">{player?.name}</span>
          </button>
        </div>
      </header>

      <main className="flex-1 w-full max-w-5xl mx-auto p-4 z-10 flex flex-col">
        {children}
      </main>

      {/* Modals */}
      <AnimatePresence>
        {showProfile && (
          <Modal onClose={() => setShowProfile(false)} title="Tu Perfil">
            <div className="space-y-4">
              <div>
                <label className="text-sm font-bold text-white/80 mb-1 block">Tu Nickname</label>
                <Input 
                  value={editName} 
                  onChange={e => setEditName(e.target.value)} 
                  maxLength={12}
                  placeholder="Ej. JuanPerez"
                />
              </div>
              <Button className="w-full" onClick={handleSaveProfile}>Guardar Cambios</Button>
            </div>
          </Modal>
        )}

        {showPremium && (
          <Modal onClose={() => setShowPremium(false)} title="STOP Premium">
            <div className="space-y-4 text-center">
              <Crown className="w-16 h-16 text-secondary mx-auto" />
              <p className="text-lg">¡Desbloquea todo el potencial!</p>
              <ul className="text-left text-sm space-y-2 bg-black/20 p-4 rounded-xl">
                <li>✨ Crea salas privadas ilimitadas</li>
                <li>✨ Sin anuncios interrupciones</li>
                <li>✨ Avatares y colores exclusivos</li>
                <li>✨ Categorías extra (Películas, Canciones...)</li>
              </ul>
              <Button variant="secondary" className="w-full mt-4" onClick={() => setShowPremium(false)}>
                Próximamente...
              </Button>
            </div>
          </Modal>
        )}
      </AnimatePresence>
    </div>
  );
}

function Modal({ children, title, onClose }: { children: ReactNode, title: string, onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <motion.div 
        initial={{ opacity: 0 }} 
        animate={{ opacity: 1 }} 
        exit={{ opacity: 0 }}
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      <motion.div 
        initial={{ scale: 0.9, opacity: 0, y: 20 }} 
        animate={{ scale: 1, opacity: 1, y: 0 }} 
        exit={{ scale: 0.9, opacity: 0, y: 20 }}
        className="bg-card border-2 border-white/10 rounded-2xl p-6 w-full max-w-md shadow-2xl relative z-10"
      >
        <h2 className="text-2xl font-display font-bold mb-6 text-center">{title}</h2>
        {children}
      </motion.div>
    </div>
  );
}
