import { Router, type IRouter } from "express";
import healthRouter from "./health";
import gameRouter from "./game";
import rankingRouter from "./ranking";
import roomsRouter from "./rooms";
import authRouter from "./auth";
import stripeRouter from "./stripe";
import presenceRouter from "./presence";
import friendsRouter from "./friends";
import dailyRouter from "./daily";
import impossibleRouter from "./impossible";
import notificationsRouter from "./notifications";
import tournamentsRouter from "./tournaments";
import seasonRouter from "./season";
import inventoryRouter from "./inventory";
import rewardsRouter from "./rewards";
import playBillingRouter from "./playBilling";
import customPacksRouter from "./customPacks";
import guestStatsRouter from "./guestStats";
import { requireRoomMemberIdentity } from "../middlewares/roomMemberAuth";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/game", gameRouter);
router.use("/ranking", rankingRouter);
router.use("/rooms", requireRoomMemberIdentity, roomsRouter);
router.use("/auth", authRouter);
router.use("/stripe", stripeRouter);
router.use("/presence", presenceRouter);
router.use("/friends", friendsRouter);
router.use("/daily", dailyRouter);
router.use("/impossible", impossibleRouter);
router.use("/notifications", notificationsRouter);
router.use("/tournaments", tournamentsRouter);
router.use("/season", seasonRouter);
router.use("/inventory", inventoryRouter);
router.use("/rewards", rewardsRouter);
router.use("/billing/play", playBillingRouter);
router.use("/custom-packs", customPacksRouter);
router.use("/guest-stats", guestStatsRouter);

export default router;
