import { Router } from "express";
import { db, playerScoresTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { verifyClaimedIdentity } from "../lib/playerAuth";
const router=Router();type CollectionMap=Record<string,unknown>;
function parseObject(raw:string|null|undefined):CollectionMap{try{const p=JSON.parse(raw||"{}");return p&&typeof p==="object"&&!Array.isArray(p)?p as CollectionMap:{};}catch{return{}}}
function parseArray(raw:string|null|undefined):string[]{try{const p=JSON.parse(raw||"[]");return Array.isArray(p)?p.filter((v):v is string=>typeof v==="string"):[]}catch{return[]}}
router.get("/progress/:playerId",async(req,res)=>{const playerId=String(req.params.playerId||"").trim();if(!playerId)return res.status(400).json({error:"Missing playerId",collectedWords:{},achievements:[]});try{const rows=await db.select({collectedWordsJson:playerScoresTable.collectedWordsJson,achievementsJson:playerScoresTable.achievementsJson,coins:playerScoresTable.coins,xp:playerScoresTable.xp,level:playerScoresTable.level}).from(playerScoresTable).where(eq(playerScoresTable.playerId,playerId)).limit(1);if(!rows.length)return res.json({playerId,collectedWords:{},achievements:[],stats:{coins:0,xp:0,level:1}});return res.json({playerId,collectedWords:parseObject(rows[0].collectedWordsJson),achievements:parseArray(rows[0].achievementsJson),stats:{coins:rows[0].coins??0,xp:rows[0].xp??0,level:rows[0].level??1}})}catch(error){console.error("[ranking/progress] GET failed:",error);return res.status(500).json({error:"Could not load progress",collectedWords:{},achievements:[]})}});
router.post("/progress/:playerId",async(req,res)=>{const playerId=String(req.params.playerId||"").trim();if(!playerId)return res.status(400).json({error:"Missing playerId"});if(!verifyClaimedIdentity(req,playerId))return res.status(403).json({error:"Identity verification failed"});const incoming=req.body?.collectedWords;if(!incoming||typeof incoming!=="object"||Array.isArray(incoming))return res.status(400).json({error:"Invalid collectedWords"});try{const rows=await db.select({id:playerScoresTable.id,collectedWordsJson:playerScoresTable.collectedWordsJson}).from(playerScoresTable).where(eq(playerScoresTable.playerId,playerId)).limit(1);if(!rows.length)return res.status(404).json({error:"Player not found"});const current=parseObject(rows[0].collectedWordsJson);const merged:CollectionMap={...current};for(const[key,value]of Object.entries(incoming as CollectionMap))if(!(key in merged))merged[key]=value;await db.update(playerScoresTable).set({collectedWordsJson:JSON.stringify(merged),updatedAt:new Date()}).where(eq(playerScoresTable.id,rows[0].id));return res.json({ok:true,playerId,collectedWords:merged})}catch(error){console.error("[ranking/progress] POST failed:",error);return res.status(500).json({error:"Could not save progress"})}});
export default router;
