import { useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { apiFetch } from "./api";

const LETTERS = "ABCDEFGHJKLMNÑPQRSTVWXYZ".split("");
const CATEGORIES = [{ key: "nombre", label: "Nombre" }, { key: "animal", label: "Animal" }, { key: "lugar", label: "Lugar" }, { key: "objeto", label: "Objeto" }, { key: "marca", label: "Marca" }];
const ROUND_SECONDS = 60;
type ValidationResult = { results: Record<string, { player: { response: string; isValid: boolean; score: number }; ai: { response: string; isValid: boolean; score: number } }>; playerTotalScore: number; aiTotalScore: number };
function randomLetter() { return LETTERS[Math.floor(Math.random() * LETTERS.length)]; }

export function GameScreen({ onExit }: { onExit: () => void }) {
  const [letter, setLetter] = useState(randomLetter); const [answers, setAnswers] = useState<Record<string, string>>({}); const [seconds, setSeconds] = useState(ROUND_SECONDS); const [phase, setPhase] = useState<"playing" | "validating" | "results">("playing"); const [result, setResult] = useState<ValidationResult | null>(null); const [error, setError] = useState<string | null>(null); const submitted = useRef(false);
  const progress = useMemo(() => seconds / ROUND_SECONDS, [seconds]);
  useEffect(() => { if (phase !== "playing") return; if (seconds <= 0) { submitRound(); return; } const timer = setTimeout(() => setSeconds(v => v - 1), 1000); return () => clearTimeout(timer); }, [seconds, phase]);
  async function submitRound() { if (submitted.current || phase !== "playing") return; submitted.current = true; setPhase("validating"); setError(null); const playerResponses = CATEGORIES.map(c => ({ category: c.key, word: answers[c.key]?.trim() ?? "" })); try { const data = await apiFetch<ValidationResult>("/api/game/validate", { method: "POST", body: JSON.stringify({ letter, language: "es", playerResponses }) }); setResult(data); setPhase("results"); } catch (err) { submitted.current = false; setPhase("playing"); setError(err instanceof Error ? err.message : "No se ha podido validar la partida."); } }
  function resetRound() { setLetter(randomLetter()); setAnswers({}); setSeconds(ROUND_SECONDS); setResult(null); setError(null); submitted.current = false; setPhase("playing"); }
  if (phase === "validating") return <SafeAreaView style={styles.safeArea}><View style={styles.center}><ActivityIndicator size="large" /><Text style={styles.heading}>Comprobando tus respuestas…</Text><Text style={styles.muted}>El servidor de STOP está validando la ronda.</Text></View></SafeAreaView>;
  if (phase === "results" && result) return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>RESULTADOS</Text><Text style={styles.heading}>¡Ronda terminada!</Text><View style={styles.scoreCard}><Text style={styles.scoreLabel}>Tu puntuación</Text><Text style={styles.score}>{result.playerTotalScore}</Text></View>{CATEGORIES.map(c => { const row = result.results[c.key]; if (!row) return null; return <View key={c.key} style={styles.resultRow}><View style={styles.resultMain}><Text style={styles.category}>{c.label}</Text><Text style={styles.answer}>{row.player.response || "—"}</Text><Text style={styles.ai}>IA: {row.ai.response || "—"}</Text></View><Text style={styles.points}>{row.player.score} pts</Text></View>; })}<TouchableOpacity style={styles.primary} onPress={resetRound}><Text style={styles.primaryText}>Jugar otra ronda</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={onExit}><Text style={styles.secondaryText}>Volver al inicio</Text></TouchableOpacity></ScrollView></SafeAreaView>;
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.topBar}><TouchableOpacity onPress={onExit}><Text style={styles.back}>‹ Volver</Text></TouchableOpacity><Text style={styles.timer}>{seconds}s</Text></View><View style={styles.letterCard}><Text style={styles.letterLabel}>LETRA</Text><Text style={styles.letter}>{letter}</Text><View style={styles.progressTrack}><View style={[styles.progress, { width: `${Math.max(0, progress) * 100}%` }]} /></View></View><Text style={styles.heading}>¡Escribe una palabra por categoría!</Text>{CATEGORIES.map(c => <View key={c.key} style={styles.field}><Text style={styles.category}>{c.label}</Text><TextInput value={answers[c.key] ?? ""} onChangeText={value => setAnswers(cur => ({ ...cur, [c.key]: value }))} placeholder={`Empieza por ${letter}…`} autoCapitalize="sentences" autoCorrect={false} returnKeyType="next" style={styles.input} /></View>)}{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.stopButton} onPress={submitRound} activeOpacity={0.85}><Text style={styles.stopText}>🛑 STOP</Text></TouchableOpacity></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safeArea:{flex:1,backgroundColor:"#f7f8fc"}, content:{padding:20,paddingBottom:40}, topBar:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:18}, back:{fontSize:16,fontWeight:"700",color:"#151f63"}, timer:{fontSize:18,fontWeight:"900"}, letterCard:{backgroundColor:"#151f63",borderRadius:24,padding:22,alignItems:"center",marginBottom:20}, letterLabel:{color:"white",opacity:.75,fontSize:12,fontWeight:"800",letterSpacing:2}, letter:{color:"white",fontSize:72,lineHeight:82,fontWeight:"900"}, progressTrack:{width:"100%",height:6,backgroundColor:"rgba(255,255,255,.25)",borderRadius:3,overflow:"hidden"}, progress:{height:"100%",backgroundColor:"white"}, heading:{fontSize:23,fontWeight:"800",marginBottom:18}, kicker:{fontSize:12,fontWeight:"900",letterSpacing:2,marginBottom:5}, field:{marginBottom:14}, category:{fontSize:15,fontWeight:"800",marginBottom:7}, input:{backgroundColor:"white",borderWidth:1,borderColor:"#dfe2eb",borderRadius:14,paddingHorizontal:15,paddingVertical:13,fontSize:17}, stopButton:{marginTop:8,backgroundColor:"#151f63",borderRadius:18,paddingVertical:17,alignItems:"center"}, stopText:{color:"white",fontSize:20,fontWeight:"900"}, error:{color:"#b42318",marginBottom:10,lineHeight:20}, center:{flex:1,alignItems:"center",justifyContent:"center",padding:30}, muted:{color:"#656a79",marginTop:10,textAlign:"center",lineHeight:22}, scoreCard:{backgroundColor:"#151f63",borderRadius:22,padding:22,alignItems:"center",marginBottom:18}, scoreLabel:{color:"white",opacity:.8,fontWeight:"700"}, score:{color:"white",fontSize:54,fontWeight:"900",marginTop:3}, resultRow:{backgroundColor:"white",borderRadius:16,padding:15,marginBottom:9,flexDirection:"row",alignItems:"center"}, resultMain:{flex:1}, answer:{fontSize:16,fontWeight:"700",marginTop:3}, ai:{color:"#777b89",fontSize:13,marginTop:4}, points:{fontSize:16,fontWeight:"900"}, primary:{backgroundColor:"#151f63",borderRadius:15,paddingVertical:15,alignItems:"center",marginTop:12}, primaryText:{color:"white",fontSize:16,fontWeight:"900"}, secondary:{paddingVertical:15,alignItems:"center"}, secondaryText:{color:"#151f63",fontWeight:"800"} });
